---

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_count: 6
    ubuntu1604_ami: ami-d15a75c7
    # problems arose with ubuntu (starting dcos-link service
    centos7_ami: ami-ae7bfdb8
  tasks:

  - ec2:                        # FIXME: this works on my EC2 account. You should adjust for yours
      key_name: gambit
      instance_type: t2.large
      image: "{{ centos7_ami }}"
      count: "{{ instance_count }}"
      wait: yes
      group_id: sg-79ba4207
      vpc_subnet_id: subnet-e3092f86
      assign_public_ip: yes
    register: ec2

  - shell: ./mk-inventory

