---

agent_list:
{% for host in groups['agent'] %}
- {{ hostvars[host].ansible_eth0.ipv4.address }}
{% endfor %}

bootstrap_url: file:///opt/dcos_install_tmp
cluster_name: {{ cluster_name }}
exhibitor_storage_backend: static
master_discovery: static

# ip_detect_public_filename: {{ ansible_user_dir }}/genconf/ip-detect
## above not used due to bug in dcos_generate_config.sh so use the default

master_list:
{% for host in groups['master'] %}
  - {{ hostvars[host].ansible_eth0.ipv4.address }}
{% endfor %}

public_agent_list:
  - {{ hostvars[groups['public-agent'][0]].ansible_eth0.ipv4.address }}

resolvers:
  - 8.8.4.4
  - 8.8.8.8

ssh_port: 22
ssh_user: {{ ansible_user_id }}
use_proxy: 'false'

# ssh_key_path: {{ ansible_user_dir }}/.ssh/id_rsa
## above not used due to bug in dcos_generate_config.sh so use default genconf/ssh_key


